#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
	/config

# copy config files
PREV_DIR=$(pwd)

	cd /defaults/html || exit
	shopt -s globstar nullglob
	for i in *
 	do
	[[ ! -e "/config/www/${i}" ]] && cp -r "${i}" "/config/www/${i}"
	done

cd "${PREV_DIR}" || exit

cp /defaults/default /config/nginx/site-confs/

# If $REMOVE_SETUP_DIRS is set remove the install and updater directories if they exist
if [ "true" == "$REMOVE_SETUP_DIRS" ] || ( [ ! -z ${INSTALL+x} ] && ["true" != "$INSTALL"] ); then
    if [ -d /config/www/install/ ]; then
        rm -R /config/www/install/
    fi
    if [ -d /config/www/updater/ ]; then
        rm -R /config/www/updater/
    fi
fi

