#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/www

# moving files
[[ ! -f /config/www/index.php ]] &&
	mv /defaults/html/* /config/www/

# copy config files
[[ ! -f /config/www/config.php ]] && \
        cp /config/www/config.php.template /config/www/config.php
chmod 664 /config/www/config.php

# permissions
chown -R abc:abc \
        /config 

# If $REMOVE_SETUP_DIRS is set remove the install and updater directories if they exist
if [ "true" == "$REMOVE_SETUP_DIRS" ] || ( [ ! -z ${INSTALL+x} ] && ["true" != "$INSTALL"] ); then
    if [ -d /config/www/install/ ]; then
        rm -R /config/www/install/
    fi
    if [ -d /config/www/updater/ ]; then
        rm -R /config/www/updater/
    fi
fi

